'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'phones',
      [
        {
          brand: 'Samsung',
          model: 'Galaxy S21',
          manufactured_year: 2021,
          ram_size: 8,
          cpu: 'Exynos 2100',
          screen_diagonal: 6.2,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Xiaomi',
          model: 'Redmi Note 10',
          manufactured_year: 2020,
          ram_size: 6,
          cpu: 'Snapdragon 678',
          screen_diagonal: 6.4,
          is_nfc: true,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Huawei',
          model: 'P40',
          manufactured_year: 2020,
          ram_size: 8,
          cpu: 'Kirin 990',
          screen_diagonal: 6.1,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Apple',
          model: 'iPhone 6',
          manufactured_year: 2014,
          ram_size: 1,
          cpu: 'A8',
          screen_diagonal: 4.7,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Nokia',
          model: '3310',
          manufactured_year: 2010,
          ram_size: 0,
          cpu: 'None',
          screen_diagonal: 1.5,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Motorola',
          model: 'Razr',
          manufactured_year: 2010,
          ram_size: 0,
          cpu: 'Unknown',
          screen_diagonal: 2.2,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Google',
          model: 'Pixel 5',
          manufactured_year: 2021,
          ram_size: 8,
          cpu: 'Snapdragon 765G',
          screen_diagonal: 6.0,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Sony',
          model: 'Xperia 1 II',
          manufactured_year: 2020,
          ram_size: 8,
          cpu: 'Snapdragon 865',
          screen_diagonal: 6.5,
          is_nfc: true,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'LG',
          model: 'G7 ThinQ',
          manufactured_year: 2018,
          ram_size: 4,
          cpu: 'Snapdragon 845',
          screen_diagonal: 6.1,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'Asus',
          model: 'ROG Phone 5',
          manufactured_year: 2021,
          ram_size: 16,
          cpu: 'Snapdragon 888',
          screen_diagonal: 6.78,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
        {
          brand: 'HTC',
          model: 'Desire 820',
          manufactured_year: 2014,
          ram_size: 2,
          cpu: 'Snapdragon 615',
          screen_diagonal: 5.5,
          is_nfc: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        },
      ],
      {}
    );
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('phones', null, {});
  },
};
